# =============================================================================
# modules/rds — Managed PostgreSQL for the core-api
#
# What this creates:
#   1. DB subnet group spanning all private subnets (multi-AZ failover surface)
#   2. Security group allowing 5432 from the EKS node SG only
#   3. Master password generated + stored in AWS Secrets Manager
#   4. RDS instance with backups, encryption, deletion protection
#
# Why the password lives in Secrets Manager and not as a Terraform variable:
#   - Terraform vars end up in plaintext in the state file. Anything in
#     state is anyone-with-S3-read's plaintext too.
#   - random_password generated here IS in state — but that's tolerable
#     because the canonical copy lives in Secrets Manager. Losing state is
#     not a credential-leak event (the password isn't rotated by losing state).
#   - In-cluster apps fetch the password via External Secrets Operator (ESO)
#     reading the Secrets Manager secret. The DB password never appears in
#     Git, env-var declarations, or pod spec.
# =============================================================================

# -----------------------------------------------------------------------------
# DB subnet group — tells RDS which subnets it can place ENIs in.
# -----------------------------------------------------------------------------

resource "aws_db_subnet_group" "this" {
  name       = "${var.identifier}-subnets"
  subnet_ids = var.private_subnet_ids

  tags = {
    Name = "${var.identifier}-subnets"
  }
}

# -----------------------------------------------------------------------------
# Security group — 5432 from EKS nodes only.
# -----------------------------------------------------------------------------

resource "aws_security_group" "this" {
  name        = "${var.identifier}-sg"
  description = "RDS security group. Ingress on 5432 from EKS nodes only."
  vpc_id      = var.vpc_id

  tags = {
    Name = "${var.identifier}-sg"
  }
}

# for_each over the caller-supplied list. Separate aws_security_group_rule
# resources (instead of inline `ingress` blocks) lets the caller add new SGs
# later without recreating the security group itself.
resource "aws_security_group_rule" "from_eks_nodes" {
  for_each = toset(var.allowed_security_group_ids)

  description              = "PostgreSQL from EKS node SG ${each.value}"
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.this.id
  source_security_group_id = each.value
}

# -----------------------------------------------------------------------------
# Master password — generated by Terraform, stored in Secrets Manager.
# -----------------------------------------------------------------------------

resource "random_password" "master" {
  length  = 32
  special = true

  # Exclude characters that need shell escaping. Saves headaches when a DBA
  # copies the password into a psql one-liner.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "master_password" {
  name        = "${var.identifier}/master-password"
  description = "RDS master password for ${var.identifier}."

  # 7-day recovery window — accidentally deleted secrets can be restored.
  # 0 = immediate hard delete. 30 = max (AWS default).
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "master_password" {
  secret_id = aws_secretsmanager_secret.master_password.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
  })
}

# -----------------------------------------------------------------------------
# RDS instance
# -----------------------------------------------------------------------------

resource "aws_db_instance" "this" {
  identifier = var.identifier

  engine         = "postgres"
  engine_version = "16.3"
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.allocated_storage * 5 # storage autoscale ceiling
  storage_type          = "gp3"
  storage_encrypted     = true # KMS-encrypted at rest (AWS-managed key)

  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]
  publicly_accessible    = false # private subnets only

  # Multi-AZ failover: standby replica in another AZ, ~60s failover on outage.
  multi_az = true

  # Backups — daily snapshots retained for 7 days. Real prod often 30 days.
  backup_retention_period = 7
  backup_window           = "03:00-04:00" # UTC, low-traffic window
  maintenance_window      = "Mon:04:00-Mon:05:00"

  # Final snapshot on delete + deletion protection = belt-and-suspenders.
  skip_final_snapshot       = false
  final_snapshot_identifier = "${var.identifier}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"
  deletion_protection       = true

  # Performance Insights — query-level latency surfaced in the RDS console.
  performance_insights_enabled = true

  # CloudWatch logs — Postgres logs streamed for retention beyond what local
  # log files keep.
  enabled_cloudwatch_logs_exports = ["postgresql"]

  tags = {
    Name = var.identifier
  }

  # CLAUDE.md: prevent_destroy on every stateful resource. Even if someone
  # `terraform destroy`s the root module, this resource refuses until the
  # lifecycle block is removed in a separate commit.
  lifecycle {
    prevent_destroy = true

    # `password` is held in Secrets Manager; rotating it there shouldn't
    #     churn the DB instance every plan.
    # `final_snapshot_identifier` includes timestamp() which changes on
    #     every plan; ignore the diff so plans don't show spurious updates.
    ignore_changes = [
      password,
      final_snapshot_identifier,
    ]
  }
}
