apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-api
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    deployment-mode: aws
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jimmy-do/k8s-gitops-delivery-platform.git
    targetRevision: main
    path: container-platform/helm/core-api
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: core-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
